### ISSUE TITLE
API access to CI builds via JSON

### ISSUE THREAD

**Issue by kdurrance** [poggit/support#53]
Hi team - I see there is a published API for JSON access to "Releases" via https://poggit.pmmp.io/releases.json, which works great.

Is there a similar API that I can use to get a list of all the builds within the CI section of Poggit?

Thx.

**Comment by Awzaw** [comment]
Please refer to #46 - there isn't yet, for the reasons @SOF3 outlines there.

**Comment by SOF3** [comment]
Actually the "Recent Builds" page should not have existed in the first place. It was never intended for people to find random plugins

**Comment by kdurrance** [comment]
Considering there is a GUI for the CI "Recent Builds" today that is usable by all (even if not originally intended), then I would have thought API access would make a lot of sense to offer a consistent interface across all of poggit? 

I also don't see a whole lot of downside in "finding random plugins" - all part of fostering a healthy, curious community IMHO.

**Comment by SOF3** [comment]
We don't want people to prefer looking at CI Recent Builds (/ci/recent) rather than looking at the approved releases (/plugins).

**Comment by SOF3** [comment]
Some data for reference: Among the 650 sessions visiting Poggit in the last week, 183 started at /, 177 started at /plugins (or /pi), 54 started at a certain plugin release page (/p/*), and 95 started at /ci/recent (or /ci). Among the 183 sessions starting at /, 74 went to /plugins the next step, 57 went to /ci/recent (or /ci), and 8 went to specific plugin release pages (/p/*).

This shows that a notable proportion of users are still looking at /ci rather than /plugins to explore plugins, and we wish to minimize this proportion before introducing an API for CI builds.

**Comment by SOF3** [comment]
In addition, I still fail to see why "recent builds" shall be useful. I can understand if repo-specific or project-specific data shall be useful, but not random builds.

**Comment by kdurrance** [comment]
CI builds definitely are living a little dangerously, but that is the nature of using dev builds. It's not like Pocketmine itself is really out of "dev" either TBH, so CI builds can be handy especially when there is an API bump. I'm not specifically looking for "random" builds, but I do follow recent builds for specific plugins that I enjoy testing with my kids.

I guess the counter question is, if users of poggit are seemingly getting value from going there by looking at your stats, why not embrace it? 

I think the platform is awesome, and I certainly understand the difference between CI and Release builds.

**Comment by SOF3** [comment]
Whether it is "in dev" is one thing, whether it is safe is another thing. You won't know if the plugin developer secretly shipped a virus with the plugin, unless you checked it really carefully.
