### ISSUE TITLE
Rejected plugin

### ISSUE THREAD

**Issue by PiloudeDakar** [poggit/support#98]
### Issue description

I submited my plugin (RankShop) to poggit twice, and it have been rejected and I don't find why. The plugin work, I haven't copied it, and the documentation is good. 
Is it possible to know why ?

### Other information
- Link to repository: https://github.com/PiloudeDakar/RankShop/tree/main/

**Comment by VixikHD** [comment]
FormAPI should be included as virion

**Comment by PiloudeDakar** [comment]
Where can i mention it ?

**Comment by VixikHD** [comment]
Read [those rules](https://poggit.pmmp.io/rules.edit), I was writing about rule **C1b (Stay in your namespace)**, _'All classes, interfaces and traits declared by plugins must be under this unique namespace (or subnamespaces). This includes libraries bundled with the plugin. Consider using the [virion framework](https://poggit.pmmp.io/virion), which provides a convenient way of shading libraries (i.e. refactoring libraries into your plugins namespace).'_. Although it is under plugin's namespace, reviewers may have problems with that it's not shipped as regular virion. Another problem might be rule **C3 (Permission names)**, _'If the plugin registers permissions, all permission names must start with the plugin name (does not need to contain the author name like the namespace). The permission name should only consist of alphabets, digits, hyphens and dots.'_ Also they might deny that because plugins EconomyAPI and PurePerms are not supported anymore.

**Comment by PiloudeDakar** [comment]
I haven't understood how I need to register the lib namespace : `namespace PiloudeDakar\RankShop\libs\jojoe77777\FormAPI;` isn't good ?

**Comment by JaxkDev** [comment]
If a plugin has been reviewed you will find a github comment on the commit that was submitted, unless it was approved in which case no github comment will be displayed.

**Comment by PiloudeDakar** [comment]
Thanks
